spring:
  application:
    name: Virtuber

  datasource:
    url: jdbc:mysql://localhost:3306/virtuber?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8000

jwt:
  secret: ${JWT_SECRET:TiMxINeC90ihi4b3NFA1v9ZBLdCKJL5Y3QvxoJMzN03}
  access-token-expiration-ms: 1800000 # 30분
  refresh-token-expiration-ms: 1209600000 # 14일

stock:
  price-update:
    fixed-delay-ms: 10000
    initial-delay-ms: 5000
    min-rate: -0.01
    max-rate: 0.01